spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    # server should not register it sef as a server
    register-with-eureka: false
    # prevents fetching its own service list
    fetch-registry: false
